// Compares the runtime dependency closure in package-lock.json with the reviewed inventory in
// docs/runtime-dependencies.txt, so a PR that adds or removes a runtime package shows up as a
// diff of that file. Also fails if any runtime package has an install script.
//
//   npm run deps:check            verify
//   npm run deps:check -- --write update the inventory after reviewing the change
import { readFileSync, writeFileSync } from 'node:fs';

const INVENTORY = new URL('../docs/runtime-dependencies.txt', import.meta.url);
const HEADER =
  '# Runtime npm packages (direct and transitive), generated by `npm run deps:check -- --write`.\n' +
  '# Adding a line here needs a review under docs/adr/0007-external-dependencies.md.\n';

interface LockEntry {
  dev?: boolean;
  devOptional?: boolean;
  hasInstallScript?: boolean;
}

const lock = JSON.parse(readFileSync(new URL('../package-lock.json', import.meta.url), 'utf8')) as {
  packages: Record<string, LockEntry>;
};

const runtime = Object.entries(lock.packages).filter(
  ([path, entry]) =>
    path.startsWith('node_modules/') && entry.dev !== true && entry.devOptional !== true,
);
const names = [
  ...new Set(runtime.map(([path]) => path.slice(path.lastIndexOf('node_modules/') + 13))),
].sort();
const withInstallScripts = runtime.filter(([, entry]) => entry.hasInstallScript === true);

const expected = HEADER + names.join('\n') + '\n';
let failed = false;

if (withInstallScripts.length > 0) {
  console.error(
    `runtime packages with install scripts: ${withInstallScripts.map(([path]) => path).join(', ')}`,
  );
  failed = true;
}

if (process.argv.includes('--write')) {
  writeFileSync(INVENTORY, expected);
  console.log(`wrote ${names.length} runtime packages to docs/runtime-dependencies.txt`);
} else {
  let current = '';
  try {
    current = readFileSync(INVENTORY, 'utf8');
  } catch {
    // Missing inventory is reported as a difference below.
  }
  if (current !== expected) {
    console.error(
      'runtime dependencies differ from docs/runtime-dependencies.txt.\n' +
        `actual: ${names.join(', ')}\n` +
        'Review the change, then run `npm run deps:check -- --write` and commit the result.',
    );
    failed = true;
  } else {
    console.log(`runtime dependencies match the inventory (${names.length} packages)`);
  }
}
process.exitCode = failed ? 1 : 0;
